### Create a new user

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Sign in with a given email and password

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Find a particular user with a given ID

GET http://localhost:3000/auth/1

### Get the currently signed in user

GET http://localhost:3000/auth/whoami

### Find all users with with a given ID

GET http://localhost:3000/auth?email=test@domain.com

### Delete a user with a given ID

DELETE http://localhost:3000/auth/2

### Update a user with a given ID

PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "password": "my-new-password"
}
